import type { GenerateOptions, GenerateResult } from "@/types/design";

export async function generateWithFal(
  prompt: string,
  _options?: GenerateOptions,
): Promise<GenerateResult> {
  const start = Date.now();

  const response = await fetch("https://queue.fal.run/fal-ai/flux/dev", {
    method: "POST",
    headers: {
      Authorization: `Key ${process.env.FAL_KEY}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      prompt,
      image_size: "square",
      num_images: 1,
    }),
  });

  if (!response.ok) {
    throw new Error(`fal.ai error: ${response.status} ${response.statusText}`);
  }

  const data = await response.json();
  const image = data.images?.[0];
  if (!image?.url) throw new Error("No image generated by fal.ai");

  return {
    imageUrl: image.url,
    imagePath: "",
    provider: "fal",
    model: "flux-dev",
    generationTimeMs: Date.now() - start,
  };
}
