import { GoogleGenAI } from "@google/genai";
import type { GenerateOptions, GenerateResult } from "@/types/design";

export async function generateWithGemini(
  prompt: string,
  _options?: GenerateOptions,
): Promise<GenerateResult> {
  const ai = new GoogleGenAI({ apiKey: process.env.GOOGLE_AI_API_KEY! });
  const start = Date.now();

  const response = await ai.models.generateContent({
    model: "gemini-2.5-flash-image",
    contents: prompt,
    config: {
      responseModalities: ["image", "text"],
    },
  });

  const parts = response.candidates?.[0]?.content?.parts;
  if (!parts) throw new Error("No response from Gemini");

  const imagePart = parts.find((p) => p.inlineData);
  if (!imagePart?.inlineData) throw new Error("No image generated by Gemini");

  const base64 = imagePart.inlineData.data;
  const mimeType = imagePart.inlineData.mimeType || "image/png";

  const imageUrl = `data:${mimeType};base64,${base64}`;
  const generationTimeMs = Date.now() - start;

  return {
    imageUrl,
    imagePath: "",
    provider: "gemini",
    model: "gemini-2.5-flash-image",
    generationTimeMs,
  };
}
